AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
Metrics/LineLength:
  Max: 150
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Exclude:
    - 'lib/label_templates/*'
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'test/**/*'
