inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/views_schema.rb
    - db/archived_migrations/*
    - vendor/**/*
Style/FileName:
  Exclude:
    - Gemfile
# Offense count: 202
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 150
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Exclude:
    - 'lib/label_templates/*'
