# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ed8bb043a555b97a80f8c07d37b9dc21fdf25a8c787ee1a5e39e6eb1ff7b8bf632b1ee99aaf44a89f244c09827479603de9710d0a804e9bff65af353f4516fa

test:
  secret_key_base: 450e443709b66373a4f3d4dd222e36b013b04f0945ccec0b83b9c1b1e39e61a52ee621fef886fd69ec08f6fb2725d799bad839c73f3825714cbfcacfbcc21b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
